Repository openshift-eng/art-dashboard-ui, pull requests merged in 2024-11, with the labels that each got.

#132 ART-10508: add Jira and PR creation logic with submitRequest button
  components/api_calls/api_calls.js
  components/release/openshift_version_select.js
  components/self-service/new-content-done.tsx
  components/self-service/new-content-form.tsx
  components/self-service/new-content-state.tsx
  components/self-service/new-content-wizard.tsx
Labels: tide/merge-method-squash, approved, lgtm, jira/valid-reference

#135 Change the URL of Beta Build History
  .env
Labels: approved, lgtm

#137 Cache installed package list in Redis
  app.py
  requirements.txt
Labels: lgtm

#138 ART-11445 Limit the displayed results to 1000
  app.py
Labels: approved, lgtm
