Repository openshift-eng/art-dashboard-ui, pull requests merged in 2025-04, with the labels that each got.

#144 strip leading and trailing whitespaces
  app.py
Labels: lgtm

#145 Revert "ART-12168: fixed variables coming from onboarding form"
  components/self-service/new-content-done.tsx
Labels: jira/valid-reference

#148 add mbiarnes to owners
  OWNERS
Labels: approved, lgtm

#147 Add adobes1 to OWNERS
  OWNERS
Labels: approved, lgtm
